apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: ai-alm-oss
