import { JiraClient } from '../src/aialm/oss/adapter/jira.ts';
import { jiraConfig, loadDotEnv } from '../src/aialm/oss/adapter/config.ts';
import { ensureSelfAwareFields } from '../src/aialm/oss/adapter/fields-config.ts';
import { markdownToAdf } from '../src/aialm/oss/adapter/adf.ts';
loadDotEnv();
const jira=new JiraClient({config:jiraConfig()});
const cids=await ensureSelfAwareFields(jira,'WELLBEINGT');
await jira.updateState('WELLBEINGT-15', {stage:'READY', role:'AI', agent:'none'}, cids);
console.log('set READY/AI/none');
await jira.addComment('WELLBEINGT-15', markdownToAdf('✅ Approved candidate — proceed to po-analyze'));
console.log('added approval');
const iss=await jira.getIssue('WELLBEINGT-15',['*all'] as any);
console.log((iss.fields as any).status?.name);
