import { proposalIdFor } from '../shared/identity.ts';
import { hasHumanApprovalFor, type ApprovalComment } from '../shared/approval.ts';
import type { PullRequestTrace } from '../shared/models.ts';

const AI_MARK = '[AI-generated]';

export interface PrBodyInput {
  summary: string;
  externalRef: string; // owner/repo#N → "Fixes owner/repo#N"
  evidenceRefs: string[];
  limitations: string[];
  traceLink: string; // public AI-ALM execution trace (Jira project)
  disclosed?: boolean; // AI-generated contribution disclosure (safe default true)
  template?: string; // Profile.prTemplate; may use ${summary} etc.
  viewerOffer?: string;
}

export interface PrGate {
  ok: boolean;
  reason: string;
}

/** The default read-only Viewer offer (include a link to the execution trace). */
export const DEFAULT_VIEWER_OFFER =
  'Want full visibility? Reply here and we will invite your account as a read-only Viewer of the execution-trace project.';

/** Derive a stable PR idempotency key for a work-item wave. */
export function prWaveKey(workItemIds: string[]): string {
  return proposalIdFor(`PR wave\n${[...workItemIds].sort().join(',')}`);
}

/** Human approval gate: READY_FOR_PR verdict AND explicit approval, else nothing opens. */
export function prGate(verdictReady: boolean, hasApproval: boolean): PrGate {
  if (!verdictReady) return { ok: false, reason: 'verification not READY_FOR_PR (run aialm-oss-verify)' };
  if (!hasApproval) return { ok: false, reason: 'missing explicit human approval to open a public PR' };
  return { ok: true, reason: 'ready to open PR' };
}

/** True when a human comment approves opening the PR for this key. */
export function prApproved(comments: { id: string; bodyText: string; isAiGenerated?: boolean }[], key: string): boolean {
  const list: ApprovalComment[] = comments.map(c => ({ id: c.id, body: c.bodyText, isAiGenerated: c.isAiGenerated ?? c.bodyText.includes(AI_MARK) }));
  return hasHumanApprovalFor(list, key);
}

function section(title: string, body: string[]): string {
  return [`### ${title}`, ...body.map(b => `- ${b}`)].join('\n');
}

/**
 * Assemble the PR body. When a Profile template is provided, substitute its
 * ${placeholder}s and then append the trace/disclosure block (so all six
 * mandated elements are always present). Default → canonical six-section body.
 */
export function buildPrBody(input: PrBodyInput): string {
  const summary = input.summary.trim();
  const tests = input.evidenceRefs.length ? section('Tests / validation', input.evidenceRefs) : '### Tests / validation\n- (no captured evidence)';
  const limitations = input.limitations.length ? section('Known limitations', input.limitations) : '### Known limitations\n- (none recorded)';
  const disclosure = input.disclosed === false
    ? 'This contribution was prepared with AI assistance (ai-alm-oss).'
    : 'This PR was generated by an AI assistant (ai-alm-oss) as part of a governed execution trace.';
  const trace = `### Execution trace\n${input.traceLink}\n\n${input.viewerOffer ?? DEFAULT_VIEWER_OFFER}`;

  const values: Record<string, string> = {
    summary,
    issue: `Fixes ${input.externalRef}`,
    tests,
    limitations,
    disclosure,
    trace,
  };

  let body: string;
  if (input.template?.trim()) {
    body = input.template.replace(/\$\{(\w+)\}/g, (_, k: string) => values[k] ?? `\${${k}}`);
    if (!/Execution trace/i.test(body)) body += `\n\n${trace}`;
  } else {
    body = [
      `### Summary\n${summary}`,
      '',
      `Fixes ${input.externalRef}`,
      '',
      tests,
      '',
      limitations,
      '',
      disclosure,
      '',
      trace,
    ].join('\n');
  }
  return body;
}

/** Validate the assembled body contains every mandated PR element. */
export function validatePrBody(body: string, input: { externalRef: string; traceLink: string }): string[] {
  const missing: string[] = [];
  if (!body.trim()) missing.push('summary');
  if (!new RegExp(`Fixes\\s+${escapeRegex(input.externalRef)}`).test(body)) missing.push(`issue relationship (Fixes ${input.externalRef})`);
  if (!/Tests \/ validation/i.test(body)) missing.push('tests / validation');
  if (!/Known limitations/i.test(body)) missing.push('known limitations');
  if (!/AI assistant|AI assistance|AI-generated/i.test(body)) missing.push('AI-generated disclosure');
  if (!body.includes(input.traceLink)) missing.push('execution trace link');
  return missing;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Record the on-GitHub PR trace: url ↔ commits ↔ work-item ids. */
export function buildPrTrace(input: { prUrl: string; commits: string[]; workItemIds: string[] }): PullRequestTrace {
  return { prUrl: input.prUrl, commits: input.commits, workItemIds: input.workItemIds };
}
